"""initial schema

Revision ID: 31b92aee428a
Revises: 
Create Date: 2026-05-23 00:48:03.705846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b92aee428a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_marca', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marcas'))
    )
    op.create_index(op.f('ix_marcas_nome_marca'), 'marcas', ['nome_marca'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor_fipe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], name=op.f('fk_modelos_marca_id_marcas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modelos'))
    )
    op.create_index(op.f('ix_modelos_marca_id'), 'modelos', ['marca_id'], unique=False)
    op.create_index(op.f('ix_modelos_nome'), 'modelos', ['nome'], unique=False)
    op.create_table('carros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_cadastro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('combustivel', sa.String(length=20), nullable=False),
    sa.Column('num_portas', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=40), nullable=False),
    sa.Column('quilometragem', sa.Integer(), nullable=False),
    sa.Column('valor_anuncio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos.id'], name=op.f('fk_carros_modelo_id_modelos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carros'))
    )
    op.create_index(op.f('ix_carros_modelo_id'), 'carros', ['modelo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carros_modelo_id'), table_name='carros')
    op.drop_table('carros')
    op.drop_index(op.f('ix_modelos_nome'), table_name='modelos')
    op.drop_index(op.f('ix_modelos_marca_id'), table_name='modelos')
    op.drop_table('modelos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_marcas_nome_marca'), table_name='marcas')
    op.drop_table('marcas')
    # ### end Alembic commands ###
