"""check combustivel e default quilometragem

Revision ID: 6f5e40f0825f
Revises: 31b92aee428a
Create Date: 2026-05-23 01:33:17.209242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5e40f0825f'
down_revision: Union[str, Sequence[str], None] = '31b92aee428a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carros', 'quilometragem',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
    # CHECK constraint (não detectado pelo autogenerate) — garante que
    # combustivel só aceite valores do enum Combustivel.
    op.create_check_constraint(
        op.f("ck_carros_combustivel"),
        "carros",
        "combustivel IN ('GASOLINA', 'ETANOL', 'FLEX', 'DIESEL', 'GNV', 'ELETRICO', 'HIBRIDO')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_carros_combustivel"), "carros", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carros', 'quilometragem',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
